title = "Flux gitleaks config"

[allowlist]
  description = "Allowlist for test data and known non-secrets"
  paths = [
    '''\.env.example''',
    '''\.env$''',
    '''soda\.yaml\.example''',
    '''flux\.yaml\.example''',
    '''_test\.go$''',
    '''web/src/api/.*test\.ts''',
    '''web/src/.*\.test\.tsx''',
  ]
