// Package web holds the embedded SPA frontend build output.
// The dist/ directory is generated by `npm run build` and embedded
// into the Go binary at compile time via the //go:embed directive.
package web

import (
	"embed"
)

//go:embed dist

// Files is the embedded SPA filesystem containing the compiled frontend
// assets (index.html, JS bundles, CSS, and static files).
var Files embed.FS
